name: fortune
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.2
  app_tracking_transparency: ^2.0.4
  video_player: ^2.8.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  background_image: "assets/images/splash.png"
  ios: true
  android: true
  web: false

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fortuneimages/
    - assets/icons/
    - assets/fortunevideos/
    - assets/audio/
    - assets/fortuneimages/fortuneonboarding/
    - assets/fortuneimages/fortunedialogs/
    - assets/fortuneimages/fortunedaily_bonus/
    - assets/fortuneimages/fortunepair_element/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
